### ISSUE TITLE
Error loading oprf@0.0.9 - Cannot find module './tools'

### ISSUE THREAD

**Issue by e-lisa** [multiparty/oprf#1]
Looks like tools.js is missing from the build! :) When importing the library I get the following error:
```
[3] Error: Cannot find module './tools'
[3]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
[3]     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
[3]     at Module.require (internal/modules/cjs/loader.js:637:17)
[3]     at require (internal/modules/cjs/helpers.js:20:18)
[3]     at Object.<anonymous> (/home/second/valkyrie/node_modules/oprf/dist/oprf.js:5:13)
[3]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[3]     at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[3]     at Object.require.extensions.(anonymous function) [as .js] (/home/second/valkyrie/node_modules/ts-node/src/index.ts:423:14)
[3]     at Module.load (internal/modules/cjs/loader.js:599:32)
[3]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

```

If I put the tools.js file in node_modules/oprf/dist/ it "works around this problem"

Thanks!

**Comment by e-lisa** [comment]
NVM -- I did my import wrong! Sorry1

**Comment by e-lisa** [comment]
Actually, I still have the issue. I just forgot to remove 'tools.js' -- and when I did, it broke.

**Comment by lucyq** [comment]
^this has been resolved by recent update
